# This YAML file contains snapshotter & csi driver API objects,
# which are necessary to run external csi snapshotter for opensds.

kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
  labels:
    app: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
spec:
  serviceName: "csi-snapshotter-opensdsplugin"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-csi-snapshotter-opensdsplugin
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          # This should be replaced by an official k8s-csi snapshotter image when it is released.
          image: quay.io/k8scsi/csi-snapshotter:v1.0.1
          args:
            - "--snapshotter=csi-opensdsplugin"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: opensds
          image: {{ .Values.image }}
          args :
            - "--csiEndpoint=$(CSI_ENDPOINT)"
            - "--opensdsEndpoint=$(OPENSDS_ENDPOINT)"
            - "--opensdsAuthStrategy=$(OPENSDS_AUTH_STRATEGY)"
            - "-v8"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: OPENSDS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: opensdsendpoint
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: enableEncrypted
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: passwordencrypter
            - name: OPENSDS_AUTH_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: opensdsauthstrategy
            - name: OS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: osauthurl
            - name: OS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: osusername
            - name: OS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: ospassword
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: passwordencrypter
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: enableEncrypted
            - name: OS_TENANT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: ostenantname
            - name: OS_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: osprojectname
            - name: OS_USER_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: osuserdomainid
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: certificate-path
              mountPath: /opt/opensds-security
      volumes:
        - name: socket-dir
          emptyDir:
        - name: certificate-path
          hostPath:
            path: /opt/opensds-security
            type: DirectoryOrCreate
